### ISSUE TITLE
Error when training M5 model (in CARET)

### ISSUE THREAD

**Issue by drcarygrantjr** [topepo/caret#618]
The following error appears after running the train function in caret with M5... What could be the problem here? Have tried troubleshooting, without success.

> M5n <- caret::train(Q ~ ., data = testData, method = "M5", trControl = rctrl,
+                     preProc = c("center", "scale"))
Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared  
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :8     NA's   :8    
Error in train.default(x, y, weights = w, ...) : Stopping
In addition: There were 25 warnings (use warnings() to see them)
#-------------------

If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [ X] Start a new R session
- [ X] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [X ] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [x ] run `sessionInfo()`

### Minimal, reproducible example:

library(caret)
testData<-structure(list(P = c(0, 0, 2.01, 0, 0, 0, 0, 0, 0, 1.26, 1.48, 
                     42, 7.97, 0, 6.79, 14.02, 0.06, 0, 0, 0, 0, 0, 0, 6.56, 0.55, 
                     1.98, 5.36, 0, 1.11, 0, 5.16, 20.34, 0, 0, 0, 0, 0, 0, 24.23, 
                     30.47, 27.05, 8.33, 31.51, 31.93, 19.75, 0.04, 0, 0, 0, 0, 0, 
                     0, 0, 0, 0, 0, 11.96, 21.38, 19.12, 6.63, 8.53, 0, 5.58, 1.08, 
                     0, 0, 0.5, 12.18, 2.91, 3.36, 3.49, 0, 0, 0, 0, 0, 0, 0, 0.99, 
                     0, 0, 0, 0, 0, 0, 2.6, 0, 2.85, 0.2, 0, 6.51, 9.82, 0, 1.97, 
                     0.02, 0, 17.26, 0, 5.76, 11.47), Pl1d = c(0, 0, 0, 2.01, 0, 0, 
                                                               0, 0, 0, 0, 1.26, 1.48, 42, 7.97, 0, 6.79, 14.02, 0.06, 0, 0, 
                                                               0, 0, 0, 0, 6.56, 0.55, 1.98, 5.36, 0, 1.11, 0, 5.16, 20.34, 
                                                               0, 0, 0, 0, 0, 0, 24.23, 30.47, 27.05, 8.33, 31.51, 31.93, 19.75, 
                                                               0.04, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11.96, 21.38, 19.12, 6.63, 
                                                               8.53, 0, 5.58, 1.08, 0, 0, 0.5, 12.18, 2.91, 3.36, 3.49, 0, 0, 
                                                               0, 0, 0, 0, 0, 0.99, 0, 0, 0, 0, 0, 0, 2.6, 0, 2.85, 0.2, 0, 
                                                               6.51, 9.82, 0, 1.97, 0.02, 0, 17.26, 0, 5.76), Pl2d = c(0, 0, 
                                                                                                                       0, 0, 2.01, 0, 0, 0, 0, 0, 0, 1.26, 1.48, 42, 7.97, 0, 6.79, 
                                                                                                                       14.02, 0.06, 0, 0, 0, 0, 0, 0, 6.56, 0.55, 1.98, 5.36, 0, 1.11, 
                                                                                                                       0, 5.16, 20.34, 0, 0, 0, 0, 0, 0, 24.23, 30.47, 27.05, 8.33, 
                                                                                                                       31.51, 31.93, 19.75, 0.04, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11.96, 
                                                                                                                       21.38, 19.12, 6.63, 8.53, 0, 5.58, 1.08, 0, 0, 0.5, 12.18, 2.91, 
                                                                                                                       3.36, 3.49, 0, 0, 0, 0, 0, 0, 0, 0.99, 0, 0, 0, 0, 0, 0, 2.6, 
                                                                                                                       0, 2.85, 0.2, 0, 6.51, 9.82, 0, 1.97, 0.02, 0, 17.26, 0), T = c(-7.64, 
                                                                                                                                                                                       -4.88, -1.4, 0.21, -2.3, -5.27, -5.14, -5.65, -4.27, -2.69, -0.49, 
                                                                                                                                                                                       2, 0.81, -1.91, -1.67, 1.07, 0.5, -0.59, 0.61, 2.52, 2.93, 3.26, 
                                                                                                                                                                                       -0.92, -4.13, -4.72, -4.07, -2.93, -5.19, -6.97, -9.82, -8.25, 
                                                                                                                                                                                       -5.1, -6.57, -8.91, -8.15, -6.49, -8.14, -7.44, -2.62, -0.98, 
                                                                                                                                                                                       -0.65, 0.58, 1.55, 2.37, 2.3, -0.43, 0.33, 3.35, -0.38, 1.49, 
                                                                                                                                                                                       4.82, 3.06, -1.03, -3.03, -3.72, -3.19, -1.07, 0.37, -0.15, -1.7, 
                                                                                                                                                                                       -5.72, -6.83, -3.46, -0.51, 1.77, 1.52, 0.33, -1.02, -1.3, -1.05, 
                                                                                                                                                                                       0.32, 0.37, -2.69, -2.16, -0.98, -1.98, -5.43, -6.67, -5.5, -4.22, 
                                                                                                                                                                                       -4.81, -3.92, -2.58, -1.07, 0.45, 0.4, 0.01, -0.16, -0.36, 0.23, 
                                                                                                                                                                                       1.2, 0.21, -1.92, -2.09, 1.65, 2.15, 0.54, -0.23, -1.32, 0.8), 
               Tl1d = c(-6.79, -7.64, -4.88, -1.4, 0.21, -2.3, -5.27, -5.14, 
                        -5.65, -4.27, -2.69, -0.49, 2, 0.81, -1.91, -1.67, 1.07, 
                        0.5, -0.59, 0.61, 2.52, 2.93, 3.26, -0.92, -4.13, -4.72, 
                        -4.07, -2.93, -5.19, -6.97, -9.82, -8.25, -5.1, -6.57, -8.91, 
                        -8.15, -6.49, -8.14, -7.44, -2.62, -0.98, -0.65, 0.58, 1.55, 
                        2.37, 2.3, -0.43, 0.33, 3.35, -0.38, 1.49, 4.82, 3.06, -1.03, 
                        -3.03, -3.72, -3.19, -1.07, 0.37, -0.15, -1.7, -5.72, -6.83, 
                        -3.46, -0.51, 1.77, 1.52, 0.33, -1.02, -1.3, -1.05, 0.32, 
                        0.37, -2.69, -2.16, -0.98, -1.98, -5.43, -6.67, -5.5, -4.22, 
                        -4.81, -3.92, -2.58, -1.07, 0.45, 0.4, 0.01, -0.16, -0.36, 
                        0.23, 1.2, 0.21, -1.92, -2.09, 1.65, 2.15, 0.54, -0.23, -1.32
               ), Tl2d = c(-5.81, -6.79, -7.64, -4.88, -1.4, 0.21, -2.3, 
                           -5.27, -5.14, -5.65, -4.27, -2.69, -0.49, 2, 0.81, -1.91, 
                           -1.67, 1.07, 0.5, -0.59, 0.61, 2.52, 2.93, 3.26, -0.92, -4.13, 
                           -4.72, -4.07, -2.93, -5.19, -6.97, -9.82, -8.25, -5.1, -6.57, 
                           -8.91, -8.15, -6.49, -8.14, -7.44, -2.62, -0.98, -0.65, 0.58, 
                           1.55, 2.37, 2.3, -0.43, 0.33, 3.35, -0.38, 1.49, 4.82, 3.06, 
                           -1.03, -3.03, -3.72, -3.19, -1.07, 0.37, -0.15, -1.7, -5.72, 
                           -6.83, -3.46, -0.51, 1.77, 1.52, 0.33, -1.02, -1.3, -1.05, 
                           0.32, 0.37, -2.69, -2.16, -0.98, -1.98, -5.43, -6.67, -5.5, 
                           -4.22, -4.81, -3.92, -2.58, -1.07, 0.45, 0.4, 0.01, -0.16, 
                           -0.36, 0.23, 1.2, 0.21, -1.92, -2.09, 1.65, 2.15, 0.54, -0.23
               ), Ql1d = c(0.427, 0.427, 0.427, 0.427, 0.427, 0.386, 0.312, 
                           0.279, 0.279, 0.279, 0.279, 0.279, 0.566, 0.619, 0.566, 0.517, 
                           4.399, 2.913, 1.794, 1.07, 0.732, 0.517, 0.427, 0.348, 0.312, 
                           0.312, 0.279, 0.279, 0.247, 0.247, 0.219, 0.219, 0.219, 0.247, 
                           0.247, 0.247, 0.219, 0.219, 0.219, 0.219, 0.219, 0.219, 0.386, 
                           2.129, 6.738, 7.042, 5.343, 3.86, 2.913, 2.249, 1.59, 1.148, 
                           0.925, 0.793, 0.674, 0.619, 0.517, 0.517, 0.732, 1.902, 2.013, 
                           1.229, 0.857, 0.674, 0.566, 0.517, 0.517, 0.471, 0.471, 0.427, 
                           0.427, 0.386, 0.386, 0.348, 0.348, 0.348, 0.312, 0.312, 0.279, 
                           0.279, 0.247, 0.247, 0.219, 0.219, 0.192, 0.192, 0.168, 0.168, 
                           0.146, 0.146, 0.168, 0.219, 0.348, 0.386, 0.348, 0.566, 1.07, 
                           1.314, 1.148, 0.925), Ql2d = c(0.517, 0.427, 0.427, 0.427, 
                                                          0.427, 0.427, 0.386, 0.312, 0.279, 0.279, 0.279, 0.279, 0.279, 
                                                          0.566, 0.619, 0.566, 0.517, 4.399, 2.913, 1.794, 1.07, 0.732, 
                                                          0.517, 0.427, 0.348, 0.312, 0.312, 0.279, 0.279, 0.247, 0.247, 
                                                          0.219, 0.219, 0.219, 0.247, 0.247, 0.247, 0.219, 0.219, 0.219, 
                                                          0.219, 0.219, 0.219, 0.386, 2.129, 6.738, 7.042, 5.343, 3.86, 
                                                          2.913, 2.249, 1.59, 1.148, 0.925, 0.793, 0.674, 0.619, 0.517, 
                                                          0.517, 0.732, 1.902, 2.013, 1.229, 0.857, 0.674, 0.566, 0.517, 
                                                          0.517, 0.471, 0.471, 0.427, 0.427, 0.386, 0.386, 0.348, 0.348, 
                                                          0.348, 0.312, 0.312, 0.279, 0.279, 0.247, 0.247, 0.219, 0.219, 
                                                          0.192, 0.192, 0.168, 0.168, 0.146, 0.146, 0.168, 0.219, 0.348, 
                                                          0.386, 0.348, 0.566, 1.07, 1.314, 1.148), Q = c(0.427, 0.427, 
                                                                                                          0.427, 0.427, 0.386, 0.312, 0.279, 0.279, 0.279, 0.279, 0.279, 
                                                                                                          0.566, 0.619, 0.566, 0.517, 4.399, 2.913, 1.794, 1.07, 0.732, 
                                                                                                          0.517, 0.427, 0.348, 0.312, 0.312, 0.279, 0.279, 0.247, 0.247, 
                                                                                                          0.219, 0.219, 0.219, 0.247, 0.247, 0.247, 0.219, 0.219, 0.219, 
                                                                                                          0.219, 0.219, 0.219, 0.386, 2.129, 6.738, 7.042, 5.343, 3.86, 
                                                                                                          2.913, 2.249, 1.59, 1.148, 0.925, 0.793, 0.674, 0.619, 0.517, 
                                                                                                          0.517, 0.732, 1.902, 2.013, 1.229, 0.857, 0.674, 0.566, 0.517, 
                                                                                                          0.517, 0.471, 0.471, 0.427, 0.427, 0.386, 0.386, 0.348, 0.348, 
                                                                                                          0.348, 0.312, 0.312, 0.279, 0.279, 0.247, 0.247, 0.219, 0.219, 
                                                                                                          0.192, 0.192, 0.168, 0.168, 0.146, 0.146, 0.168, 0.219, 0.348, 
                                                                                                          0.386, 0.348, 0.566, 1.07, 1.314, 1.148, 0.925, 1.69)), .Names = c("P", 
                                                                                                                                                                             "Pl1d", "Pl2d", "T", "Tl1d", "Tl2d", "Ql1d", "Ql2d", "Q"), row.names = c(NA, 
                                                                                                                                                                                                                                                      100L), class = "data.frame")

rctrl <- trainControl(method = "cv", number = 3, returnResamp = "all")
set.seed(1)

M5n <- caret::train(Q ~ ., data = testData, method = "M5", trControl = rctrl,
                    preProc = c("center", "scale"))
#---- End here

_> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Cubist_0.0.19    Hmisc_4.0-2      Formula_1.2-1    gbm_2.1.1        survival_2.41-2 
 [6] openair_2.0-0    maps_3.1.1       plotrix_3.6-4    RWeka_0.4-32     C50_0.1.0-24    
[11] hydroGOF_0.3-8   zoo_1.7-14       topmodel_0.7.2-2 caret_6.0-73     ggplot2_2.2.1   
[16] lattice_0.20-34  nnet_7.3-12      e1071_1.6-8     

loaded via a namespace (and not attached):
 [1] foreach_1.4.3       assertthat_0.1      sp_1.2-4            stats4_3.3.2       
 [5] latticeExtra_0.6-28 backports_1.0.5     quantreg_5.29       automap_1.0-14     
 [9] digest_0.6.12       RColorBrewer_1.1-2  checkmate_1.8.2     minqa_1.2.4        
[13] colorspace_1.3-2    htmltools_0.3.5     Matrix_1.2-7.1      plyr_1.8.4         
[17] hydroTSM_0.4-2-1    SparseM_1.76        scales_0.4.1        intervals_0.15.1   
[21] lme4_1.1-12         MatrixModels_0.4-1  gstat_1.1-5         tibble_1.2         
[25] htmlTable_1.9       mgcv_1.8-15         car_2.1-4           DT_0.2             
[29] hexbin_1.27.1       lazyeval_0.2.0      pbkrtest_0.4-7      magrittr_1.5       
[33] nlme_3.1-128        MASS_7.3-45         xts_0.9-7           foreign_0.8-67     
[37] class_7.3-14        FNN_1.1             data.table_1.10.4   tools_3.3.2        
[41] RWekajars_3.9.1-1   stringr_1.2.0       munsell_0.4.3       cluster_2.0.5      
[45] compiler_3.3.2      spacetime_1.2-0     grid_3.3.2          nloptr_1.0.4       
[49] iterators_1.0.8     htmlwidgets_0.8     base64enc_0.1-3     partykit_1.1-1     
[53] gtable_0.2.0        ModelMetrics_1.1.0  codetools_0.2-15    DBI_0.6            
[57] reshape_0.8.6       reshape2_1.4.2      R6_2.2.0            gridExtra_2.2.1    
[61] lubridate_1.6.0     knitr_1.15.1        dplyr_0.5.0         rJava_0.9-8        
[65] stringi_1.1.2       Rcpp_0.12.10        mapproj_1.2-4       rpart_4.1-10       
[69] acepack_1.4.1  

### Session Info:
```{R}
>sessionInfo()

```

You can delete the text in each section that explains how to do it correctly.
Be sure to test your 2 chunks of code in an empty R session before submitting your issue!

**Comment by topepo** [comment]
> `In addition: There were 25 warnings (use warnings() to see them)`

Can yo print them? Also, does these work? 
```r
M5P(Q ~ ., data = testData)
M5Rules(Q ~ ., data = testData)
```

**Comment by drcarygrantjr** [comment]
> M5P(Q ~ ., data = testData)
Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

M5Rules(Q ~ ., data = testData)
Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

**I get this error for both, despite having JAVA (32/64 bit) being installed** 

> warnings()
Warning messages:
1: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=Yes, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

2: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=No, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

3: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=Yes, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

4: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=No, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

5: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=Yes, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

6: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=No, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

7: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=Yes, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

8: In eval(expr, envir, enclos) :
  model fit failed for Fold1: pruned=No, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

9: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=Yes, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

10: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=No, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

11: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=Yes, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

12: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=No, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

13: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=Yes, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

14: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=No, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

15: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=Yes, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

16: In eval(expr, envir, enclos) :
  model fit failed for Fold2: pruned=No, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

17: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=Yes, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

18: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=No, smoothed=Yes, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

19: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=Yes, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

20: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=No, smoothed=No, rules=Yes Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

21: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=Yes, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

22: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=No, smoothed=Yes, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

23: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=Yes, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

24: In eval(expr, envir, enclos) :
  model fit failed for Fold3: pruned=No, smoothed=No, rules=No Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix

25: In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  ... :
  There were missing values in resampled performance measures.

**Comment by topepo** [comment]
I've never seen those before. You might try reinstalling the `RWeka` packages and try again.

**Comment by drcarygrantjr** [comment]
I have done that several times. I suspect it has something to do with R versions, I think it was still working fine on 3.3.1

**Comment by topepo** [comment]
I'm going to close this. You should talk to the RWeka people and see if you can get `M5P` and `M5Rules` working. If those work and `train`, doesn't go ahead and reopen the issue. 

Java... ¯\_(ツ)_/¯
